In [1]:
import numpy as np
import time

a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [3]:
a = np.zeros((4,))
print(a)

[0. 0. 0. 0.]


In [4]:
a = np.random.random_sample(4)
print(a)

[0.27375369 0.03660452 0.89780823 0.83029768]


In [5]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [7]:
a = np.arange(6).reshape(-1)
print(a)


[0 1 2 3 4 5]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 2, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
